var rule = {
    title:'Missav',
    host:'https://missav.app',
    url:'/vodtype/fyclass/page/fypage/',
    headers:{
        'User-Agent':'PC_UA'
    },
    timeout:5000,
    class_name:'日本中字&国产精品&国产剧情&人妻&无码精品&欧美精品&动漫精品&综合三级&素人&有码精品',
    class_url:'28&20&20&21&22&23&24&25&21&21',
    limit:5,
    play_parse:true,
    lazy:'',
    一级:'div.thumbnail.group;img.lozad&&alt;img.lozad&&data-src;span.absolute.bottom-1.left-1&&Text;a&&href',
    二级:'*',
    searchable:0,
    quickSearch:0,
    filterable:0,
}
